### ISSUE TITLE
Overlapping interface on screen rotation in preferences page

### ISSUE THREAD

**Issue by neupanedipen** [yuzumone/Twltrus_for_twitter#1]
#### Expected behavior<br>
The app is supposed to show undistorted interface on screen rotation.<br>
#### Actual behavior<br>
But the interface is overlapped when rotating the screen after opening the settings page.<br>
#### How to reproduce<br>
1. Install the app.<br>
2. Launch the app.<br>
3. Authorize your twitter account to open with this apl.<br>
4. Click on settings option from left sliding navigation menu.<br>
5. Now change the orientation of the screen to landscape mode. <br>
The interface is overlapped and leads to unclear interface of preferences page.<br>
* App Version: 0.7.6<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/-3OSxiZVMJg<br>
#### Proof of Work Done<br>
https://github.com/neupanedipen

**Comment by yuzumone** [comment]
This issue has been fixed in v0.7.7. Thank you.
